import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"
# os.environ["MUJOCO_GL"] = "osmesa"
# os.environ["PYOPENGL_PLATFORM"] = "osmesa"
import gymnasium
import argparse
import numpy as np
from einops import rearrange
import torch
from collections import deque
from tqdm import tqdm
import colorama
import time

import pandas as pd
import wandb

from utils import seed_np_torch, WandbLogger
from replay_buffer import ReplayBuffer
import agents
from sub_models.world_models import WorldModel
from line_profiler import profile
import yaml
from envs.my_memory_maze import MemoryMaze
from envs.my_atari import Atari
from envs.my_dmc import DMControl
from eval import eval_episodes
import warnings
import ast
from pathlib import Path

# Action IDs produced by play.py key mapping and their expected ALE meanings.
PLAY_KEY_ACTION_MEANING = {
    0: "NOOP", 1: "FIRE", 2: "UP", 3: "RIGHT", 4: "LEFT", 5: "DOWN",
    6: "UPRIGHT", 7: "UPLEFT", 8: "DOWNRIGHT", 9: "DOWNLEFT", 10: "UPFIRE",
    11: "RIGHTFIRE", 12: "LEFTFIRE", 13: "DOWNFIRE", 14: "UPRIGHTFIRE",
    15: "UPLEFTFIRE", 16: "DOWNRIGHTFIRE", 17: "DOWNLEFTFIRE",
}

def _get_nested_config(config, key_path, default):
    current = config
    for key in key_path.split('.'):
        if isinstance(current, dict) and key in current:
            current = current[key]
        elif hasattr(current, key):
            current = getattr(current, key)
        else:
            return default
    return current

def _normalise_token(text):
    return "".join(ch.lower() for ch in str(text) if ch.isalnum())

def _extract_action_meanings(env):
    if hasattr(env, '_env') and hasattr(env._env, 'unwrapped') and hasattr(env._env.unwrapped, 'get_action_meanings'):
        return list(env._env.unwrapped.get_action_meanings())
    if hasattr(env, 'unwrapped') and hasattr(env.unwrapped, 'get_action_meanings'):
        return list(env.unwrapped.get_action_meanings())
    return None

def _find_demo_files(demo_dir, env_name):
    demo_root = Path(demo_dir)
    if not demo_root.exists():
        return []
    all_files = sorted(demo_root.glob('*.npz'))
    if not all_files:
        return []
    if str(env_name).startswith('ALE/'):
        game_name = str(env_name).split('/')[-1].split('-')[0]
        game_token = _normalise_token(game_name)
        matched = [file_path for file_path in all_files if game_token in _normalise_token(file_path.stem)]
        return matched
    return all_files

def _load_npz_demo(demo_path):
    with np.load(demo_path, allow_pickle=False) as data:
        required = {'obs', 'action', 'reward'}
        missing = required.difference(set(data.files))
        if missing:
            raise ValueError(f"{demo_path} is missing required keys: {sorted(missing)}")
        obs = data['obs'].copy()
        action = data['action'].copy()
        reward = data['reward'].copy()
        if 'termination' in data.files:
            termination = data['termination'].copy()
        elif 'done' in data.files:
            termination = data['done'].copy()
        else:
            raise ValueError(f"{demo_path} must include either 'termination' or 'done'.")
            
        ram = data['ram'].copy() if 'ram' in data.files else None
    return obs, action, reward, termination, ram

def _validate_demo_actions(action_array, env, strict_action_check=True):
    if action_array.size == 0:
        return action_array.astype(np.int64), []
    if np.issubdtype(action_array.dtype, np.integer):
        action_array = action_array.astype(np.int64)
    else:
        if not np.all(np.isclose(action_array, np.round(action_array))):
            raise ValueError('Demonstration action contains non-integer values.')
        action_array = np.round(action_array).astype(np.int64)
    unique_actions = sorted(np.unique(action_array).tolist())
    if hasattr(env.action_space, 'n'):
        action_n = env.action_space.n
        invalid_actions = [a for a in unique_actions if a < 0 or a >= action_n]
        if invalid_actions:
            raise ValueError(f'Demonstration action id out of range (n={action_n}): {invalid_actions}')
    if strict_action_check and hasattr(env.action_space, 'n'):
        unexpected_actions = [a for a in unique_actions if a not in PLAY_KEY_ACTION_MEANING]
        if unexpected_actions:
            raise ValueError(f'Demonstration action ids not generated by play.py mapping: {unexpected_actions}')
        action_meanings = _extract_action_meanings(env)
        if action_meanings is not None:
            mismatches = []
            for action_id in unique_actions:
                if action_id >= len(action_meanings):
                    mismatches.append((action_id, PLAY_KEY_ACTION_MEANING[action_id], 'OUT_OF_RANGE'))
                    continue
                expected = PLAY_KEY_ACTION_MEANING[action_id]
                actual = action_meanings[action_id]
                if expected != actual:
                    mismatches.append((action_id, expected, actual))
            if mismatches:
                mismatch_msg = ', '.join([f'id={aid}: expected={exp}, actual={act}' for aid, exp, act in mismatches])
                raise ValueError(f'Action meaning mismatch: {mismatch_msg}')
    return action_array, unique_actions

def preload_play_demonstrations(config, replay_buffer: ReplayBuffer, env):
    default_enable = Path('demonstrations').exists()
    use_demo = bool(_get_nested_config(config, 'Demonstration.Enable', default_enable))
    if not use_demo:
        print('Demonstration preload disabled. Skipping demo insertion.')
        return 0

    demo_dir = _get_nested_config(config, 'Demonstration.Directory', 'demonstrations')
    max_files = int(_get_nested_config(config, 'Demonstration.MaxFiles', 0))
    strict_action_check = bool(_get_nested_config(config, 'Demonstration.StrictActionCheck', True))

    demo_files = _find_demo_files(demo_dir, config.BasicSettings.Env_name)
    if max_files > 0:
        demo_files = demo_files[:max_files]

    if not demo_files:
        print(f'No demonstration files found in {demo_dir}. Training continues without preload.')
        return 0

    expected_obs_shape = tuple(replay_buffer.obs_buffer.shape[1:])
    total_steps = 0
    used_action_ids = set()
    demo_scores = []

    for demo_path in demo_files:
        if len(replay_buffer) >= replay_buffer.max_length:
            print('Replay buffer is full while loading demonstrations. Stopping preload early.')
            break

        obs, action, reward, termination, ram = _load_npz_demo(demo_path)

        if obs.ndim != 4 or tuple(obs.shape[1:]) != expected_obs_shape:
            print(f'Warning: {demo_path} observation shape mismatch. Expected (T, {expected_obs_shape[0]}, {expected_obs_shape[1]}, {expected_obs_shape[2]}), got {obs.shape}. Skipping this file.')
            continue

        if not (len(obs) == len(action) == len(reward) == len(termination)):
            print(f'Warning: {demo_path} has inconsistent lengths: obs={len(obs)}, action={len(action)}, reward={len(reward)}, termination={len(termination)}. Skipping.')
            continue
            
        if ram is not None and len(ram) != len(obs):
            print(f'Warning: {demo_path} has inconsistent lengths for ram: ram={len(ram)}. Setting ram to None.')
            ram = None

        if len(obs) == 0:
            print(f'Skipping empty demonstration file: {demo_path}')
            continue

        if obs.dtype != np.uint8:
            obs = obs.astype(np.uint8)

        action, unique_actions = _validate_demo_actions(action, env, strict_action_check=strict_action_check)
        used_action_ids.update(unique_actions)

        reward = reward.astype(np.float32)
        termination = (termination.astype(np.float32) > 0.5).astype(np.float32)
        
        demo_scores.append(float(reward.sum()))

        steps_to_insert = min(len(obs), replay_buffer.max_length - len(replay_buffer))
        if steps_to_insert < len(obs):
            print(f'Truncating {demo_path} from {len(obs)} to {steps_to_insert} steps due to replay buffer capacity.')

        for i in range(steps_to_insert):
            current_ram = ram[i] if ram is not None else None
            replay_buffer.append(obs[i], float(action[i]), float(reward[i]), float(termination[i]), ram=current_ram)

        total_steps += steps_to_insert
        print(colorama.Fore.GREEN + f"Loaded demo file: {os.path.basename(demo_path)}" + colorama.Style.RESET_ALL)

    if total_steps == 0:
        print('No demonstration transitions were loaded into replay buffer.')
        return 0

    action_meanings = _extract_action_meanings(env)
    if action_meanings is not None and used_action_ids:
        summary = ', '.join([f'{aid}:{action_meanings[aid]}' for aid in sorted(used_action_ids)])
        print(f'Validated demonstration action mapping (id:meaning): {summary}')

    print(colorama.Fore.CYAN + f'Preloaded {total_steps} demonstration transitions into replay buffer.' + colorama.Style.RESET_ALL)
    
    if demo_scores:
        if not hasattr(config, 'Demonstration'):
            config.Demonstration = DotDict({})
        config.Demonstration.Score = float(np.mean(demo_scores))
        print(colorama.Fore.GREEN + f"Calculated average demo score: {config.Demonstration.Score}" + colorama.Style.RESET_ALL)
        
    return total_steps

@profile
def train_world_model_step(replay_buffer: ReplayBuffer, world_model: WorldModel, agent: agents.ActorCriticAgent, batch_size, batch_length, logger, epoch, global_step):
    epoch_reconstruction_loss_list = []
    epoch_reward_loss_list = []
    epoch_termination_loss_list = []
    epoch_dynamics_loss_list = []
    epoch_dynamics_real_kl_div_list = []
    epoch_representation_loss_list = []
    epoch_representation_real_kl_div_list = []
    epoch_total_loss_list = []
    epoch_macro_loss_list = []
    epoch_macro_distill_loss_list = []
    epoch_macro_contrastive_loss_list = []
    
    for e in range(epoch):
        obs, action, reward, termination, indexes = replay_buffer.sample(batch_size, batch_length, imagine=False)
        (
            reconstruction_loss, reward_loss, termination_loss,
            dynamics_loss, dynamics_real_kl_div, representation_loss,
            representation_real_kl_div, total_loss,
            macro_loss, macro_distill_loss, macro_contrastive_loss
        ) = world_model.update(
            obs, action, reward, termination, 
            global_step=global_step, epoch_step=e, logger=logger,
            indexes=indexes, replay_buffer=replay_buffer, agent=agent
        )

        epoch_reconstruction_loss_list.append(reconstruction_loss)
        epoch_reward_loss_list.append(reward_loss)
        epoch_termination_loss_list.append(termination_loss)
        epoch_dynamics_loss_list.append(dynamics_loss)
        epoch_dynamics_real_kl_div_list.append(dynamics_real_kl_div)
        epoch_representation_loss_list.append(representation_loss)
        epoch_representation_real_kl_div_list.append(representation_real_kl_div)
        epoch_total_loss_list.append(total_loss)
        epoch_macro_loss_list.append(macro_loss)
        epoch_macro_distill_loss_list.append(macro_distill_loss)
        epoch_macro_contrastive_loss_list.append(macro_contrastive_loss)
        
    if logger is not None:
        logger.log("WorldModel/reconstruction_loss", np.mean(epoch_reconstruction_loss_list), global_step=global_step)
        logger.log("WorldModel/reward_loss",np.mean(epoch_reward_loss_list), global_step=global_step)
        logger.log("WorldModel/termination_loss", np.mean(epoch_termination_loss_list), global_step=global_step)
        logger.log("WorldModel/dynamics_loss", np.mean(epoch_dynamics_loss_list), global_step=global_step)
        logger.log("WorldModel/dynamics_real_kl_div", np.mean(epoch_dynamics_real_kl_div_list), global_step=global_step)
        logger.log("WorldModel/representation_loss", np.mean(epoch_representation_loss_list), global_step=global_step)
        logger.log("WorldModel/representation_real_kl_div", np.mean(epoch_representation_real_kl_div_list), global_step=global_step)
        logger.log("WorldModel/total_loss", np.mean(epoch_total_loss_list), global_step=global_step)
        logger.log("WorldModel/macro_loss", np.mean(epoch_macro_loss_list), global_step=global_step)
        logger.log("WorldModel/macro_distill_loss", np.mean(epoch_macro_distill_loss_list), global_step=global_step)
        logger.log("WorldModel/macro_contrastive_loss", np.mean(epoch_macro_contrastive_loss_list), global_step=global_step)
        
        if hasattr(world_model, 'macro_loss') and world_model.macro_loss is not None:
            logger.log("WorldModel/GlobalRebuild_Count", world_model.macro_loss.global_rebuild_count, global_step=global_step)

@profile
@torch.no_grad()
def world_model_imagine_data(replay_buffer: ReplayBuffer,
                             world_model: WorldModel, agent: agents.ActorCriticAgent,
                             imagine_batch_size,
                             imagine_context_length, imagine_batch_length,
                             log_video, logger, global_step):
    '''
    Sample context from replay buffer, then imagine data with world model and agent
    '''
    world_model.eval()
    agent.eval()
    sample_obs, sample_action, sample_reward, sample_termination, indexes = replay_buffer.sample(
        imagine_batch_size, imagine_context_length + imagine_batch_length, imagine=True)
        
    # 데모 데이터 여부를 나타내는 마스크 생성
    demo_valid_size = getattr(replay_buffer, 'protect_size', 0)
    demo_mask = indexes[:, 0] < demo_valid_size if indexes.numel() > 0 else torch.zeros(imagine_batch_size, dtype=torch.bool, device=sample_obs.device)
    
    # 컨텍스트와 상상 미래 데이터 분리
    context_obs = sample_obs[:, :imagine_context_length]
    context_action = sample_action[:, :imagine_context_length]
    context_reward = sample_reward[:, :imagine_context_length]
    context_termination = sample_termination[:, :imagine_context_length]
    future_actions = sample_action[:, imagine_context_length:]
    
    if world_model.model == 'Transformer':
        latent, action, old_logits, context_latent, reward_hat, termination_hat = world_model.imagine_data(
            agent, context_obs, context_action,
            imagine_batch_size=imagine_batch_size,
            imagine_batch_length=imagine_batch_length,
            log_video=log_video,
            logger=logger, global_step=global_step,
            demo_mask=demo_mask, future_actions=future_actions
        )
    elif world_model.model == 'Mamba' or world_model.model == 'Mamba2':
         latent, action, old_logits, context_latent, reward_hat, termination_hat = world_model.imagine_data2(
            agent, context_obs, context_action,
            imagine_batch_size=imagine_batch_size,
            imagine_batch_length=imagine_batch_length,
            log_video=log_video,
            logger=logger, global_step=global_step,
            demo_mask=demo_mask, future_actions=future_actions
        )
    return latent, action, old_logits, context_latent, context_reward, context_termination, reward_hat, termination_hat, demo_mask

@profile
def joint_train_world_model_agent(config, logdir,
                                  replay_buffer: ReplayBuffer,
                                  world_model: WorldModel, agent: agents.ActorCriticAgent,
                                  logger, demo_steps=0):
    os.makedirs(f"{logdir}/ckpt", exist_ok=True)


    if config.BasicSettings.Env_name.startswith('ALE'):
        env = Atari(config.BasicSettings.Env_name, size=config.BasicSettings.ImageSize, seed=config.BasicSettings.Seed)
        is_discrete = True
    elif config.BasicSettings.Env_name.startswith('memory'):
        env = MemoryMaze(config.BasicSettings.Env_name, size=config.BasicSettings.ImageSize, seed=config.BasicSettings.Seed)
        is_discrete = True
    elif config.BasicSettings.Env_name.startswith('dm_'):
        # Parse dm_control environment name: dm_domain_task
        # Example: dm_cheetah_run, dm_walker_walk, dm_humanoid_stand
        parts = config.BasicSettings.Env_name.split('_')
        domain_name = parts[1]
        task_name = '_'.join(parts[2:])  # Handle multi-word tasks
        env = DMControl(
            domain_name=domain_name,
            task_name=task_name,
            action_repeat=config.BasicSettings.ActionRepeat if hasattr(config.BasicSettings, 'ActionRepeat') else 2,
            size=config.BasicSettings.ImageSize,
            camera_id=config.BasicSettings.CameraId if hasattr(config.BasicSettings, 'CameraId') else 0,
            seed=config.BasicSettings.Seed,
            length=config.BasicSettings.MaxEpisodeSteps if hasattr(config.BasicSettings, 'MaxEpisodeSteps') else 1000
        )
        is_discrete = False
    else:
        assert ValueError(f'Unknown environment name: {config.BasicSettings.Env_name}')
    print("Current env: " + colorama.Fore.YELLOW + f"{config.BasicSettings.Env_name}" + colorama.Style.RESET_ALL)

    # Benchmark handling (only for Atari)
    if config.BasicSettings.Env_name.startswith('ALE'):
        atari_benchmark_df = pd.read_csv("atari_performance.csv", index_col='Task', usecols=lambda column: column in ['Task', 'Alien', 'Amidar', 'Assault', 'Asterix', 'BankHeist', 'BattleZone', 'Boxing', 'Breakout', 'ChopperCommand', 'CrazyClimber', 'DemonAttack', 'Freeway', 'Frostbite', 'Gopher', 'Hero', 'Jamesbond', 'Kangaroo', 'Krull', 'KungFuMaster', 'MsPacman', 'Pong', 'PrivateEye', 'Qbert', 'RoadRunner', 'Seaquest', 'UpNDown'])
        atari_pure_name = config.BasicSettings.Env_name.split('/')[-1].split('-')[0]
        game_benchmark_df = atari_benchmark_df.get(atari_pure_name)
    else:
        game_benchmark_df = None
    
    sum_reward = 0
    current_ob, info = env.reset()
    current_ram = info.get('ram', None)
    context_obs = deque(maxlen=config.JointTrainAgent.RealityContextLength)
    context_action = deque(maxlen=config.JointTrainAgent.RealityContextLength)

    num_envs = getattr(config.JointTrainAgent, 'NumEnvs', 1)
    
    # Demonstration의 SkipPretrain 값을 우선으로 사용, 없으면 JointTrainAgent 확인
    skip_pretrain = getattr(config.Demonstration, 'SkipPretrain', _get_nested_config(config, 'JointTrainAgent.SkipPretrain', False)) if hasattr(config, 'Demonstration') else _get_nested_config(config, 'JointTrainAgent.SkipPretrain', False)

    if demo_steps > 0 and not skip_pretrain:
        pretrain_updates = (demo_steps // num_envs) // config.JointTrainAgent.TrainDynamicsEverySteps
        print(colorama.Fore.CYAN + f"\nStarting Offline Pre-training: {pretrain_updates} updates (scaled down by num_envs={num_envs}) using demonstration data..." + colorama.Style.RESET_ALL)
        
        for p_step in tqdm(range(pretrain_updates), desc='Pre-training (Offline)'):
            pseudo_global_step = p_step * config.JointTrainAgent.TrainDynamicsEverySteps * num_envs
            
            if replay_buffer.ready('world_model'):
                wm_micro_batch_size = int(_get_nested_config(
                    config,
                    'JointTrainAgent.WorldModelMicroBatchSize',
                    config.JointTrainAgent.BatchSize,
                ))
                train_world_model_step(
                    replay_buffer=replay_buffer,
                    world_model=world_model,
                    agent=agent,
                    batch_size=config.JointTrainAgent.BatchSize,
                    batch_length=config.JointTrainAgent.BatchLength,
                    logger=logger,
                    epoch=config.JointTrainAgent.TrainDynamicsEpoch,
                    global_step=pseudo_global_step,
                )
        print(colorama.Fore.CYAN + "Offline Pre-training completed.\n" + colorama.Style.RESET_ALL)

    print(colorama.Fore.GREEN + f"\nStarting Joint Training..." + colorama.Style.RESET_ALL)
    
    performance_decay_factor = 1.0
    bc_weight_decay_factor = 1.0
    base_world_model_demo_ratio = getattr(config.Demonstration, 'WorldModelDemoRatio', 0.25) if hasattr(config, 'Demonstration') else 0.25

    # sample and train
    remaining_steps = max(0, config.JointTrainAgent.SampleMaxSteps - demo_steps)
    total_iters = config.JointTrainAgent.SampleMaxSteps // num_envs
    initial_iters = demo_steps // num_envs

    for loop_idx in tqdm(range(remaining_steps // num_envs), 
                         desc='Training',
                         initial=initial_iters,
                         total=total_iters):
        total_steps = initial_iters + loop_idx
        # sample part >>>
        if replay_buffer.ready('world_model'):
            world_model.eval()
            agent.eval()
            with torch.no_grad():
                if len(context_action) == 0:
                    action = env.action_space.sample()
                else:
                    context_latent = world_model.encode_obs(torch.cat(list(context_obs), dim=1).to(world_model.device))
                    model_context_action = np.stack(list(context_action))

                    # FIXED: Handle both discrete and continuous actions
                    if is_discrete:
                        # Discrete: shape is (L,) -> reshape to (1, L)
                        model_context_action = rearrange(torch.Tensor(model_context_action).to(world_model.device), "L -> 1 L")
                    else:
                        # Continuous: shape is (L, A) -> reshape to (1, L, A)
                        model_context_action = rearrange(torch.Tensor(model_context_action).to(world_model.device), "L A -> 1 L A")
                    
                    # 현재 프레임(current_ob)의 실제 이미지 기반 인코딩 (Posterior 역할)
                    current_obs_tensor = rearrange(torch.Tensor(current_ob).to(world_model.device), "H W C -> 1 1 C H W") / 255
                    current_latent = world_model.encode_obs(current_obs_tensor)

                    if world_model.model == 'Transformer':
                        _, last_dist_feat = world_model.calc_last_dist_feat(context_latent, model_context_action)
                    elif world_model.model == 'Mamba' or world_model.model == 'Mamba2':
                        _, last_dist_feat = world_model.calc_last_dist_feat(context_latent, model_context_action)

                    # Prior가 아닌 현재 프레임의 관측 결과(current_latent)를 바탕으로 행동 결정
                    action = agent.sample_as_env_action(
                        torch.cat([current_latent, last_dist_feat], dim=-1),
                        greedy=False
                    )[0]

            context_obs.append(rearrange(torch.Tensor(current_ob).to(world_model.device), "H W C -> 1 1 C H W")/255)
            context_action.append(action)
        else:
            action = env.action_space.sample()

        env_start_time = time.time()
        ob, reward, is_last, info = env.step(action)
        replay_buffer.append(current_ob, action, reward, info['is_terminal'], ram=current_ram)

        sum_reward += reward
        current_ob = ob
        current_ram = info.get('ram', None)

        if is_last:
            episode_score = float(sum_reward)
            logger.log(f"episode/score", episode_score, global_step=total_steps)
            
            # 성능 기반 동적 커리큘럼 로직 (Episode 점수가 데모의 k배를 넘을 때)
            if hasattr(config, 'Demonstration') and hasattr(config.Demonstration, 'Score') and hasattr(config.Demonstration, 'DemoRatioDecayScoreMultiplier'):
                target_score = config.Demonstration.Score * config.Demonstration.DemoRatioDecayScoreMultiplier
                if episode_score > target_score:
                    base_demo_decay_rate = getattr(config.Demonstration, 'DemoRatioDecayRate', 0.9)
                    base_bc_decay_rate = getattr(config.Demonstration, 'BCWeightDecayRate', 0.65)
                    base_episode_length = getattr(config.Demonstration, 'BaseEpisodeLength', 900.0)
                    
                    if demo_steps > 0:
                        decay_rate = base_demo_decay_rate ** (base_episode_length / demo_steps)
                        bc_decay_rate = base_bc_decay_rate ** (base_episode_length / demo_steps)
                    else:
                        decay_rate = base_demo_decay_rate
                        bc_decay_rate = base_bc_decay_rate

                    threshold = getattr(config.Demonstration, 'DemoRatioDecayThreshold', 0.05)
                    
                    performance_decay_factor *= decay_rate
                    if performance_decay_factor < threshold:
                        performance_decay_factor = 0.0
                        
                    bc_threshold = getattr(config.Demonstration, 'BCWeightDecayThreshold', 0.1)
                    
                    bc_weight_decay_factor *= bc_decay_rate
                    if bc_weight_decay_factor < bc_threshold:
                        bc_weight_decay_factor = 0.0
                        
                    # World Model의 데모 훈련 비율 하한선 업데이트
                    replay_buffer.world_model_demo_ratio = base_world_model_demo_ratio * performance_decay_factor
                    if logger is not None:
                        logger.log("Demonstration/WorldModelDemoRatio", replay_buffer.world_model_demo_ratio, global_step=total_steps)

            logger.log(f"episode/length", info["episode_frame_number"], global_step=total_steps)  # framskip=4
            if config.BasicSettings.Env_name.startswith('ALE'):
                logger.log(f"episode/normalised score", (sum_reward - game_benchmark_df['Random'])/(game_benchmark_df['Human'] - game_benchmark_df['Random']), global_step=total_steps)
                for algorithm in game_benchmark_df.index[2:]:
                    denominator = game_benchmark_df[algorithm] - game_benchmark_df['Random']
                    if denominator != 0:
                        normalized_score = (sum_reward - game_benchmark_df['Random']) / denominator
                        logger.log(f"benchmark/normalised {algorithm} score", normalized_score, global_step=total_steps)
            
            sum_reward = 0
            ob, info = env.reset()
            current_ob = ob
            current_ram = info.get('ram', None)
            context_obs.clear()
            context_action.clear()

        env_time = time.time() - env_start_time
        world_model_time = 0.0
        agent_time = 0.0

        if replay_buffer.ready('world_model') and total_steps % (config.JointTrainAgent.TrainDynamicsEverySteps // config.JointTrainAgent.NumEnvs) == 0 and total_steps <= config.JointTrainAgent.FreezeWorldModelAfterSteps:
            wm_start_time = time.time()
            train_world_model_step(
                replay_buffer,
                world_model,
                agent,
                config.JointTrainAgent.BatchSize,
                config.JointTrainAgent.BatchLength,
                logger,
                config.JointTrainAgent.TrainDynamicsEpoch,
                total_steps
            )
            world_model_time = time.time() - wm_start_time


        if replay_buffer.ready('behaviour') and total_steps % (config.JointTrainAgent.TrainAgentEverySteps // config.JointTrainAgent.NumEnvs) == 0 and total_steps <= config.JointTrainAgent.FreezeBehaviourAfterSteps:
            agent_start_time = time.time()
            log_video = total_steps % (config.JointTrainAgent.SaveEverySteps // config.JointTrainAgent.NumEnvs) == 0

            # Agent의 데모 비율 커리큘럼 스케줄링 로직 적용
            if hasattr(config, 'Demonstration') and config.Demonstration.Enable:
                start_step = getattr(config.Demonstration, 'AgentDemoRatioStartStep', 10000)
                peak_step = getattr(config.Demonstration, 'AgentDemoRatioPeakStep', 20000)
                end_step = getattr(config.Demonstration, 'AgentDemoRatioEndStep', 100000)
                peak_ratio = getattr(config.Demonstration, 'AgentDemoRatioPeak', 0.5)
                end_ratio = getattr(config.Demonstration, 'AgentDemoRatioEnd', 0.1)

                if total_steps < start_step:
                    agent_ratio = 0.0
                elif total_steps < peak_step:
                    # Linearly increase to peak
                    progress = (total_steps - start_step) / (peak_step - start_step)
                    agent_ratio = progress * peak_ratio
                elif total_steps < end_step:
                    # Linearly decrease from peak to end_ratio
                    progress = (total_steps - peak_step) / (end_step - peak_step)
                    agent_ratio = peak_ratio - progress * (peak_ratio - end_ratio)
                else:
                    agent_ratio = end_ratio

                # Apply decay
                agent_ratio *= performance_decay_factor
                replay_buffer.agent_demo_ratio = agent_ratio
                logger.log("Demonstration/AgentDemoRatio", agent_ratio, global_step=total_steps)

            imagine_latent, agent_action, old_logits, context_latent, context_reward, context_termination, imagine_reward, imagine_termination, demo_mask = world_model_imagine_data(
                replay_buffer=replay_buffer,
                world_model=world_model,
                agent=agent,
                imagine_batch_size=config.JointTrainAgent.ImagineBatchSize,
                imagine_context_length=config.JointTrainAgent.ImagineContextLength,
                imagine_batch_length=config.JointTrainAgent.ImagineBatchLength,
                log_video=log_video,
                logger=logger,
                global_step=total_steps
            )

            agent.update(
                latent=imagine_latent,
                action=agent_action,
                old_logits=old_logits,
                context_latent=context_latent,
                context_reward=context_reward,
                context_termination=context_termination,
                reward=imagine_reward,
                termination=imagine_termination,
                logger=logger,
                global_step=total_steps,
                demo_mask=demo_mask,
                performance_decay_factor=performance_decay_factor,
                bc_weight_decay_factor=bc_weight_decay_factor
            )
            agent_time = time.time() - agent_start_time

        if total_steps % 100 == 0:
            pass # Time logging removed at user request

        if config.Evaluate.DuringTraining and total_steps % (config.Evaluate.EverySteps // config.JointTrainAgent.NumEnvs) == 0:
            _ = eval_episodes(config, world_model, agent, logger, total_steps, logdir=logdir)

            
            if hasattr(world_model, 'macro_loss') and hasattr(world_model.macro_loss, 'log_detailed_distribution'):
                world_model.macro_loss.log_detailed_distribution(logger, total_steps, replay_buffer=replay_buffer)
        if config.JointTrainAgent.SaveModels and total_steps % (config.JointTrainAgent.SaveEverySteps // config.JointTrainAgent.NumEnvs) == 0:
            print(colorama.Fore.GREEN + f"Saving model at total steps {total_steps}" + colorama.Style.RESET_ALL)
            torch.save(world_model.state_dict(), f"{logdir}/ckpt/world_model.pth")
            torch.save(agent.state_dict(), f"{logdir}/ckpt/agent.pth")



def build_world_model(conf, action_dim, device):
    return WorldModel(
        action_dim = action_dim,
        config = conf, 
        device = device
    ).cuda(device)


def build_agent(conf, action_dim, device):
    if conf.Models.Agent.Policy == 'AC':
        return agents.ActorCriticAgent(
            conf = conf,
            action_dim=action_dim,
            device = device
        ).cuda(device)
    elif conf.Models.Agent.Policy == 'PPO':
        return agents.PPOAgent(
            conf=conf,
            action_dim=action_dim,
            device = device
        ).cuda(device)        


class DotDict(dict):
    """Dictionary with dot notation access."""
    def __init__(self, *args, **kwargs):
        super(DotDict, self).__init__(*args, **kwargs)
        for key, value in self.items():
            if isinstance(value, dict):
                self[key] = DotDict(value)

    def __getattr__(self, item):
        try:
            value = self[item]
        except KeyError:
            raise AttributeError(f"'DotDict' object has no attribute '{item}'")
        if isinstance(value, dict) and not isinstance(value, DotDict):
            value = DotDict(value)
            self[item] = value
        return value

    __setattr__ = dict.__setitem__
    __delattr__ = dict.__delitem__

    def update_or_create(self, key_path, value):
        keys = key_path.split('.')
        d = self
        for key in keys[:-1]:
            if key not in d or not isinstance(d[key], dict):
                d[key] = DotDict()
            d = d[key]
        d[keys[-1]] = value

# Function to parse and update config from arguments
def parse_args_and_update_config(config, prefix=''):
    parser = argparse.ArgumentParser()

    # Map string dtype to torch dtype
    def dtype_mapper(dtype_str):
        dtype_map = {
            'float32': torch.float32,
            'float16': torch.float16,
            'bfloat16': torch.bfloat16
        }
        return dtype_map[dtype_str]

    def add_arguments(config, prefix=''):
        for key, value in config.items():
            if isinstance(value, dict):
                add_arguments(value, prefix + key + '.')
            elif isinstance(value, bool):
                # Special handling for boolean arguments
                parser.add_argument(f'--{prefix}{key}', type=lambda x: x.lower() in ['true', '1', 'yes'], default=value)
            elif key == 'dtype':
                # Special handling for dtype arguments
                parser.add_argument(f'--{prefix}{key}', type=dtype_mapper, default=value)
            elif isinstance(value, (list, dict)):
                # Use a custom converter for list/dict-like arguments
                parser.add_argument(f'--{prefix}{key}', type=lambda x: ast.literal_eval(x), default=value)
            else:
                parser.add_argument(f'--{prefix}{key}', type=type(value), default=value)

    def update_dict(d, keys, value):
        for key in keys[:-1]:
            d = d.setdefault(key, {})
        d[keys[-1]] = value

    add_arguments(config, prefix)
    
    args = parser.parse_args()
    args_dict = vars(args)
    
    for arg_key, arg_value in args_dict.items():
        if arg_value is not None:
            keys = arg_key.split('.')
            update_dict(config, keys, arg_value)
    
    return config

def update_model_parameters(config, world_model, agent):
    config.update_or_create('Models.WorldModel.TotalParamNum', sum([p.numel() for p in world_model.parameters()]))
    print(f'World model total parameters: {sum([p.numel() for p in world_model.parameters()]):,}')
    
    config.update_or_create('Models.WorldModel.BackboneParamNum', sum([p.numel() for p in world_model.sequence_model.parameters()]))
    print(f'Dynamic model parameters: {sum([p.numel() for p in world_model.sequence_model.parameters()]):,}')
    
    config.update_or_create('Models.WorldModel.EncoderParamNum', sum([p.numel() for p in world_model.encoder.parameters()]))
    print(f'Encoder parameters: {sum([p.numel() for p in world_model.encoder.parameters()]):,}')
    
    config.update_or_create('Models.WorldModel.DecoderParamNum', sum([p.numel() for p in world_model.image_decoder.parameters()]))
    print(f'Decoder parameters: {sum([p.numel() for p in world_model.image_decoder.parameters()]):,}')
    
    config.update_or_create('Models.WorldModel.DiscretisationLayerParamNum', sum([p.numel() for p in world_model.dist_head.parameters()]))
    print(f'Discretisation layer parameters: {sum([p.numel() for p in world_model.dist_head.parameters()]):,}')
    
    config.update_or_create('Models.Agent.ActorParamNum', sum([p.numel() for p in agent.actor.parameters()]))
    print(f'Actor parameters: {sum([p.numel() for p in agent.actor.parameters()]):,}')
    
    config.update_or_create('Models.Agent.CriticParamNum', sum([p.numel() for p in agent.critic.parameters()]))
    print(f'Critic parameters: {sum([p.numel() for p in agent.critic.parameters()]):,}')

if __name__ == "__main__":
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    torch.backends.cudnn.benchmark = True
    warnings.filterwarnings("ignore")

    with open('config_files/configure.yaml', 'r') as file:
        config = yaml.safe_load(file)

    config = parse_args_and_update_config(config)   
    config = DotDict(config)

    # Init Env
    if config.BasicSettings.Env_name.startswith('ALE'):
        env = Atari(config.BasicSettings.Env_name, size=config.BasicSettings.ImageSize, seed=config.BasicSettings.Seed)
        is_discrete = True
    elif config.BasicSettings.Env_name.startswith('memory'):
        env = MemoryMaze(config.BasicSettings.Env_name, size=config.BasicSettings.ImageSize, seed=config.BasicSettings.Seed)
        is_discrete = True
    elif config.BasicSettings.Env_name.startswith('dm_'):
        parts = config.BasicSettings.Env_name.split('_')
        domain_name = parts[1]
        task_name = '_'.join(parts[2:])
        env = DMControl(
            domain_name=domain_name,
            task_name=task_name,
            action_repeat=config.BasicSettings.ActionRepeat if hasattr(config.BasicSettings, 'ActionRepeat') else 2,
            size=config.BasicSettings.ImageSize,
            camera_id=config.BasicSettings.CameraId if hasattr(config.BasicSettings, 'CameraId') else 0,
            seed=config.BasicSettings.Seed,
            length=config.BasicSettings.MaxEpisodeSteps if hasattr(config.BasicSettings, 'MaxEpisodeSteps') else 1000
        )
        is_discrete = False
    else:
        raise ValueError(f'Unknown environment name: {config.BasicSettings.Env_name}')

    device = torch.device(config.BasicSettings.Device)
    # set seed
    seed_np_torch(seed=config.BasicSettings.Seed)

    # build replay buffer
    replay_buffer = ReplayBuffer(config, device=device)


    action_dim = env.action_space.n if is_discrete else env.action_space.shape[0]

    # build world model and agent
    world_model = build_world_model(config, action_dim, device)
    agent = build_agent(config, action_dim, device)
    update_model_parameters(config, world_model, agent)
    if (config.BasicSettings.Compile and os.name != "nt"):  # compilation is not supported on windows
        world_model = torch.compile(world_model)
        agent = torch.compile(agent)
    if config.BasicSettings.SavePath != 'None':
        print('Loading models')
        world_model.load_state_dict(torch.load(f"{config.BasicSettings.SavePath}/world_model.pth"))
        agent.load_state_dict(torch.load(f"{config.BasicSettings.SavePath}/agent.pth"))
   
    with open('/media/storage_data/ai2lab/choemj/Drama/.wandb_api_key', 'r') as f:
        wandb_key = f.read().strip()
    wandb.login(key=wandb_key)
    logger = WandbLogger(config=config, project=config.Wandb.Init.Project, mode=config.Wandb.Init.Mode)
    logdir = f"./saved_models/{config.n}/{config.BasicSettings.Env_name}/{logger.run.id}"

    # Preload demonstrations
    demo_steps = preload_play_demonstrations(config, replay_buffer, env)

    # Update max lengths if needed based on demo_steps
    if demo_steps > 0:
        replay_buffer.protect_size = demo_steps

    # train
    joint_train_world_model_agent(config, logdir, replay_buffer, world_model, agent, logger, demo_steps=demo_steps)

    logger.close()
